### ISSUE TITLE
More details in README

### ISSUE THREAD

**Issue by zamber** [orbitturner/ORBIT-ENCODER#1]
**Is your feature request related to a problem? Please describe.**
It's not really clear what compression algo is used and what's it's performance.

**Describe the solution you'd like**
A clear readme with the algo used, why it was chosen and how it compares to other algorithms / libraries. After testing with my demo dataset this lib is really slow on compression and super fast on decompression. I'm searching for something that will be fast both ways and it would be nice to cross out a lib at first glance without testing :P.

**Describe alternatives you've considered**
ZLib, LZ77, LZW, Zip, probably others.

**Comment by orbitturner** [comment]
Hello zamber,

**First thing fisrt**, thanks for the time you've taken to test the library and for your comment.

It is necessary to know that this bookshop was born after a problem that I had during a project and that it was necessary to regulate very quickly therefore it was made in not even 03 days. After that i didn't want to overload the README with these.
 
Under the hood, I use the **LZ-string algorithm for compression**. 

Initially, the lz-string-js was designed by @pieroxy to fulfill the need of storing large amounts of data in localStorage, specifically on mobile devices. localStorage being usually limited to 5MB, all you can compress is that much more data you can store. 

### What about other libraries?
All I could find was:

[some LZW implementations](http://rosettacode.org/wiki/LZW_compression#JavaScript) which gives you back arrays of numbers (terribly inefficient to store as tokens take 64bits) and don't support any character above 255.
[some other LZW implementations](https://gist.github.com/revolunet/843889) which gives you back a string (less terribly inefficient to store but still, all tokens take 16 bits) and don't support any character above 255.
[an LZMA implementation](https://github.com/nmrugg/LZMA-JS) that is asynchronous and very slow - but hey, it's LZMA, not the implementation that is slow.
[a GZip implementation](https://github.com/beatgammit/gzip-js) not really meant for browsers but meant for node.js, which weighted 70kb (with deflate.js and crc32.js on which it depends).

### And Remeber, My needs were:

- Working on mobile I needed something fast.

- Working with Strings gathered from outside my website, I needed something that can take any kind of string as an input, including any UTF characters above 255.

- The library not taking 70kb was a definitive plus.

- Something that produces strings as compact as possible to store in localStorage.

So none of the libraries I could find online worked well for my needs.

### Performance
For performace comparison, we use LZMA level 1 as a comparison point.

- For strings smaller than 750 characters, this program is 10x faster than LZMA level 1. It produces smaller output.

- For strings smaller than 100 000 characters, this program is 10x faster than LZMA level 1. It produces bigger output.

- For strings bigger than 750 000 characters, this program is slower than LZMA level 1. It produces bigger output.

**Comment by zamber** [comment]
Tried the same implementations you did and all of them were either slow or failed with higher UTF chars.

Eventually it boiled down to jszip and LZUTF8 for me, with LZUTF8 being around 20% faster (and less boilerplate to compress down strings). Both handle UTF8 > 255 fine and both can compress down to base64. The compression ratio can be a bit lower than your implementation though, haven't checked it.
